// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';

export class ClubStatsService extends BaseService {
  /**
   * Retrieve current statistics for a specific club.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getCurrentClubStats(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/club-stats/{team}/now',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    return this.client.call(request);
  }

  /**
   * Returns an overview of the stats for each season for a specific club.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamClubStatsSeason(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/club-stats-season/{team}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    return this.client.call(request);
  }

  /**
   * Retrieve the stats for a specific team, season, and game type.
   * @param {string} team - Three-letter team code
   * @param {number} season - Season in YYYYYYYY format
   * @param {number} gameType - Game type (2 for regular season, 3 for playoffs)
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getClubStatsBySeason(
    team: string,
    season: number,
    gameType: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/club-stats/{team}/{season}/{game-type}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    request.addPathParam('season', season);
    request.addPathParam('game-type', gameType);
    return this.client.call(request);
  }
}
