// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';

export class ClubStatsService extends BaseService {
  /**
   * Retrieve current statistics for a specific club.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getCurrentClubStats(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/club-stats/{team}/now', { team: team });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }

  /**
   * Returns an overview of the stats for each season for a specific club.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamClubStatsSeason(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/club-stats-season/{team}', { team: team });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }

  /**
   * Retrieve the stats for a specific team, season, and game type.
   * @param {string} team - Three-letter team code
   * @param {number} season - Season in YYYYYYYY format
   * @param {number} gameType - Game type (2 for regular season, 3 for playoffs)
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getClubStatsBySeason(
    team: string,
    season: number,
    gameType: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/club-stats/{team}/{season}/{game-type}', {
      team: team,
      season: season,
      'game-type': gameType,
    });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }
}
