// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const abstractGameState = z.enum(['Live', 'Preview']);

export type AbstractGameState = z.infer<typeof abstractGameState>;
