// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const contributors = z.object({
  name: z.string().optional(),
  twitter: z.string().optional(),
});

/**
 *
 * @typedef  {Contributors} contributors
 * @property {string}
 * @property {string}
 */
export type Contributors = z.infer<typeof contributors>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const contributorsResponse = z
  .object({
    name: z.string().optional(),
    twitter: z.string().optional(),
  })
  .transform((data) => ({
    name: data['name'],
    twitter: data['twitter'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const contributorsRequest = z
  .object({ name: z.string().nullish(), twitter: z.string().nullish() })
  .transform((data) => ({
    name: data['name'],
    twitter: data['twitter'],
  }));
