// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const datetime = z.object({
  dateTime: z.string().optional(),
  endDateTime: z.string().optional(),
});

/**
 *
 * @typedef  {Datetime} datetime
 * @property {string}
 * @property {string}
 */
export type Datetime = z.infer<typeof datetime>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const datetimeResponse = z
  .object({
    dateTime: z.string().optional(),
    endDateTime: z.string().optional(),
  })
  .transform((data) => ({
    dateTime: data['dateTime'],
    endDateTime: data['endDateTime'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const datetimeRequest = z
  .object({ dateTime: z.string().nullish(), endDateTime: z.string().nullish() })
  .transform((data) => ({
    dateTime: data['dateTime'],
    endDateTime: data['endDateTime'],
  }));
