// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { gameDecisionPlayer, gameDecisionPlayerRequest, gameDecisionPlayerResponse } from './game-decision-player';

/**
 * The shape of the model inside the application code - what the users use
 */
export const decisions = z.object({
  winner: gameDecisionPlayer.optional(),
  loser: gameDecisionPlayer.optional(),
  firstStar: gameDecisionPlayer.optional(),
  secondStar: gameDecisionPlayer.optional(),
  thirdStar: gameDecisionPlayer.optional(),
});

/**
 *
 * @typedef  {Decisions} decisions
 * @property {GameDecisionPlayer}
 * @property {GameDecisionPlayer}
 * @property {GameDecisionPlayer}
 * @property {GameDecisionPlayer}
 * @property {GameDecisionPlayer}
 */
export type Decisions = z.infer<typeof decisions>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const decisionsResponse = z
  .object({
    winner: gameDecisionPlayerResponse.optional(),
    loser: gameDecisionPlayerResponse.optional(),
    firstStar: gameDecisionPlayerResponse.optional(),
    secondStar: gameDecisionPlayerResponse.optional(),
    thirdStar: gameDecisionPlayerResponse.optional(),
  })
  .transform((data) => ({
    winner: data['winner'],
    loser: data['loser'],
    firstStar: data['firstStar'],
    secondStar: data['secondStar'],
    thirdStar: data['thirdStar'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const decisionsRequest = z
  .object({
    winner: gameDecisionPlayerRequest.nullish(),
    loser: gameDecisionPlayerRequest.nullish(),
    firstStar: gameDecisionPlayerRequest.nullish(),
    secondStar: gameDecisionPlayerRequest.nullish(),
    thirdStar: gameDecisionPlayerRequest.nullish(),
  })
  .transform((data) => ({
    winner: data['winner'],
    loser: data['loser'],
    firstStar: data['firstStar'],
    secondStar: data['secondStar'],
    thirdStar: data['thirdStar'],
  }));
