// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const detailedState = z.enum(['In Progress', 'Pre-Game']);

export type DetailedState = z.infer<typeof detailedState>;
