// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { divisionConference, divisionConferenceRequest, divisionConferenceResponse } from './division-conference';

/**
 * The shape of the model inside the application code - what the users use
 */
export const division = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
  link: z.string().optional(),
  abbreviation: z.string().optional(),
  conference: divisionConference.optional(),
  active: z.boolean().optional(),
});

/**
 *
 * @typedef  {Division} division
 * @property {number}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {DivisionConference}
 * @property {boolean}
 */
export type Division = z.infer<typeof division>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const divisionResponse = z
  .object({
    id: z.number().optional(),
    name: z.string().optional(),
    link: z.string().optional(),
    abbreviation: z.string().optional(),
    conference: divisionConferenceResponse.optional(),
    active: z.boolean().optional(),
  })
  .transform((data) => ({
    id: data['id'],
    name: data['name'],
    link: data['link'],
    abbreviation: data['abbreviation'],
    conference: data['conference'],
    active: data['active'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const divisionRequest = z
  .object({
    id: z.number().nullish(),
    name: z.string().nullish(),
    link: z.string().nullish(),
    abbreviation: z.string().nullish(),
    conference: divisionConferenceRequest.nullish(),
    active: z.boolean().nullish(),
  })
  .transform((data) => ({
    id: data['id'],
    name: data['name'],
    link: data['link'],
    abbreviation: data['abbreviation'],
    conference: data['conference'],
    active: data['active'],
  }));
