// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const gameHighlightType1 = z.enum(['video']);

export type GameHighlightType1 = z.infer<typeof gameHighlightType1>;
