// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const gamesVenue = z.object({
  name: z.string().optional(),
  link: z.string().optional(),
});

/**
 *
 * @typedef  {GamesVenue} gamesVenue
 * @property {string}
 * @property {string}
 */
export type GamesVenue = z.infer<typeof gamesVenue>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const gamesVenueResponse = z
  .object({
    name: z.string().optional(),
    link: z.string().optional(),
  })
  .transform((data) => ({
    name: data['name'],
    link: data['link'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const gamesVenueRequest = z
  .object({ name: z.string().nullish(), link: z.string().nullish() })
  .transform((data) => ({
    name: data['name'],
    link: data['link'],
  }));
