// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { gameBoxscoreTeam, gameBoxscoreTeamRequest, gameBoxscoreTeamResponse } from './game-boxscore-team';

/**
 * The shape of the model inside the application code - what the users use
 */
export const gameBoxscoreTeams = z.object({
  away: gameBoxscoreTeam.optional(),
  home: gameBoxscoreTeam.optional(),
});

/**
 *
 * @typedef  {GameBoxscoreTeams} gameBoxscoreTeams
 * @property {GameBoxscoreTeam}
 * @property {GameBoxscoreTeam}
 */
export type GameBoxscoreTeams = z.infer<typeof gameBoxscoreTeams>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const gameBoxscoreTeamsResponse = z
  .object({
    away: gameBoxscoreTeamResponse.optional(),
    home: gameBoxscoreTeamResponse.optional(),
  })
  .transform((data) => ({
    away: data['away'],
    home: data['home'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const gameBoxscoreTeamsRequest = z
  .object({ away: gameBoxscoreTeamRequest.nullish(), home: gameBoxscoreTeamRequest.nullish() })
  .transform((data) => ({
    away: data['away'],
    home: data['home'],
  }));
