// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const gameEditorialKeywordType = z.enum([
  'bodyParagraphCount',
  'bodyWordCount',
  'clob_autoTagSkip_playerCards',
  'content',
  'embeddable',
  'gameId',
  'language',
  'playerId',
  'previewParagraphCount',
  'primaryTag',
  'previewWordCount',
  'shareable',
  'statsEventId',
  'teamFileCode',
  'teamId',
]);

export type GameEditorialKeywordType = z.infer<typeof gameEditorialKeywordType>;
