// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getTeamsExpand = z.enum(['team.roster', 'team.schedule.next', 'team.schedule.previous']);

export type GetTeamsExpand = z.infer<typeof getTeamsExpand>;
