// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const officialType = z.enum(['Linesman', 'Referee']);

export type OfficialType = z.infer<typeof officialType>;
