// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const official = z.object({
  id: z.number().optional(),
  fullName: z.string().optional(),
  link: z.string().optional(),
});

/**
 *
 * @typedef  {Official} official
 * @property {number}
 * @property {string}
 * @property {string}
 */
export type Official = z.infer<typeof official>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const officialResponse = z
  .object({
    id: z.number().optional(),
    fullName: z.string().optional(),
    link: z.string().optional(),
  })
  .transform((data) => ({
    id: data['id'],
    fullName: data['fullName'],
    link: data['link'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const officialRequest = z
  .object({ id: z.number().nullish(), fullName: z.string().nullish(), link: z.string().nullish() })
  .transform((data) => ({
    id: data['id'],
    fullName: data['fullName'],
    link: data['link'],
  }));
