// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const playersPerson = z.object({
  id: z.number().optional(),
  fullName: z.string().optional(),
  link: z.string().optional(),
  shootsCatches: z.string().optional(),
  rosterStatus: z.string().optional(),
});

/**
 *
 * @typedef  {PlayersPerson} playersPerson
 * @property {number}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type PlayersPerson = z.infer<typeof playersPerson>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const playersPersonResponse = z
  .object({
    id: z.number().optional(),
    fullName: z.string().optional(),
    link: z.string().optional(),
    shootsCatches: z.string().optional(),
    rosterStatus: z.string().optional(),
  })
  .transform((data) => ({
    id: data['id'],
    fullName: data['fullName'],
    link: data['link'],
    shootsCatches: data['shootsCatches'],
    rosterStatus: data['rosterStatus'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const playersPersonRequest = z
  .object({
    id: z.number().nullish(),
    fullName: z.string().nullish(),
    link: z.string().nullish(),
    shootsCatches: z.string().nullish(),
    rosterStatus: z.string().nullish(),
  })
  .transform((data) => ({
    id: data['id'],
    fullName: data['fullName'],
    link: data['link'],
    shootsCatches: data['shootsCatches'],
    rosterStatus: data['rosterStatus'],
  }));
