// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const playbacksName = z.enum([
  'FLASH_192K_320X180',
  'FLASH_450K_400X224',
  'FLASH_1200K_640X360',
  'FLASH_1800K_960X540',
  'HTTP_CLOUD_MOBILE',
  'HTTP_CLOUD_TABLET',
  'HTTP_CLOUD_TABLET_60',
  'HTTP_CLOUD_WIRED',
  'HTTP_CLOUD_WIRED_60',
  'HTTP_CLOUD_WIRED_WEB',
]);

export type PlaybacksName = z.infer<typeof playbacksName>;
