// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const shootoutInfoAway = z.object({
  scores: z.number().optional(),
  attempts: z.number().optional(),
});

/**
 *
 * @typedef  {ShootoutInfoAway} shootoutInfoAway
 * @property {number}
 * @property {number}
 */
export type ShootoutInfoAway = z.infer<typeof shootoutInfoAway>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const shootoutInfoAwayResponse = z
  .object({
    scores: z.number().optional(),
    attempts: z.number().optional(),
  })
  .transform((data) => ({
    scores: data['scores'],
    attempts: data['attempts'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const shootoutInfoAwayRequest = z
  .object({ scores: z.number().nullish(), attempts: z.number().nullish() })
  .transform((data) => ({
    scores: data['scores'],
    attempts: data['attempts'],
  }));
