// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const standingsType = z.enum(['regularSeason']);

export type StandingsType = z.infer<typeof standingsType>;
