// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { awayLeagueRecord1, awayLeagueRecord1Request, awayLeagueRecord1Response } from './away-league-record-1';
import { awayTeam1, awayTeam1Request, awayTeam1Response } from './away-team-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const teamsAway1 = z.object({
  leagueRecord: awayLeagueRecord1.optional(),
  score: z.number().optional(),
  team1: awayTeam1.optional(),
});

/**
 *
 * @typedef  {TeamsAway1} teamsAway1
 * @property {AwayLeagueRecord1}
 * @property {number}
 * @property {AwayTeam1}
 */
export type TeamsAway1 = z.infer<typeof teamsAway1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const teamsAway1Response = z
  .object({
    leagueRecord: awayLeagueRecord1Response.optional(),
    score: z.number().optional(),
    team: awayTeam1Response.optional(),
  })
  .transform((data) => ({
    leagueRecord: data['leagueRecord'],
    score: data['score'],
    team1: data['team'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const teamsAway1Request = z
  .object({
    leagueRecord: awayLeagueRecord1Request.nullish(),
    score: z.number().nullish(),
    team1: awayTeam1Request.nullish(),
  })
  .transform((data) => ({
    leagueRecord: data['leagueRecord'],
    score: data['score'],
    team: data['team1'],
  }));
