// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const tokenDataType = z.enum(['hyperLink', 'playerCard']);

export type TokenDataType = z.infer<typeof tokenDataType>;
