// This file was generated by liblab | https://liblab.com/

import { GetScheduleExpand, getScheduleExpand } from './models';

export interface GetScheduleParams {
  expand?: GetScheduleExpand;
  teamId?: string;
  startDate?: string;
  endDate?: string;
}
