// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';

export class ScheduleService extends BaseService {
  /**
   * Retrieve the next game for a specific team.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamNextGame(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/schedule/{team}/next',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    return this.client.call(request);
  }

  /**
   * Retrieve the schedule for a specific team and season.
   * @param {string} team - Three-letter team code
   * @param {number} season - Season in YYYYYYYY format
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamScheduleBySeason(
    team: string,
    season: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/schedule/{team}/{season}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    request.addPathParam('season', season);
    return this.client.call(request);
  }

  /**
   * Retrieve the statistics for a specific game.
   * @param {number} season - Season in YYYYYYYY format
   * @param {string} team - Three-letter team code
   * @param {number} game - Game ID
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getGameStats(
    season: number,
    team: string,
    game: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/schedule/{season}/team/{team}/game/{game}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('season', season);
    request.addPathParam('team', team);
    request.addPathParam('game', game);
    return this.client.call(request);
  }
}
