// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';

export class ScoreboardService extends BaseService {
  /**
   * Retrieve the scoreboard for a specific team as of the current moment.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getCurrentTeamScoreboard(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/v1/scoreboard/{team}/now',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('team', team);
    return this.client.call(request);
  }
}
