// This file was generated by liblab | https://liblab.com/

export interface GetCurrentGoalieStatsLeadersParams {
  categories?: string;
  limit?: number;
}

export interface GetGoalieStatsLeadersParams {
  categories?: string;
  limit?: number;
}
