// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { StatTypes, statTypesResponse } from './models';

export class StatsService extends BaseService {
  /**
   *
   * @returns {Promise<HttpResponse<StatTypes[]>>} OK
   */
  async getStatTypes(requestConfig?: RequestConfig): Promise<HttpResponse<StatTypes[]>> {
    const path = '/statTypes';
    const options: any = {
      responseSchema: z.array(statTypesResponse),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
