// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';

export class StandingsService extends BaseService {
  /**
   * Retrieve the standings as of the current moment.
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getCurrentStandings(requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = '/v1/standings/now';
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }

  /**
   * Retrieve the standings for a specific date.
   * @param {string} date - Date in YYYY-MM-DD format
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getStandingsByDate(date: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/standings/{date}', { date: date });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }

  /**
   * Retrieves information for each season's standings.
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getStandingsSeason(requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = '/v1/standings-season';
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }
}
