// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getStandingsByTypeType = z.enum([
  'byConference',
  'byDivision',
  'byLeague',
  'divisionLeaders',
  'postseason',
  'preseason',
  'regularSeason',
  'wildCard',
  'wildCardWithLeaders',
]);

export type GetStandingsByTypeType = z.infer<typeof getStandingsByTypeType>;
