// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const standingTypes = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

/**
 *
 * @typedef  {StandingTypes} standingTypes
 * @property {string}
 * @property {string}
 */
export type StandingTypes = z.infer<typeof standingTypes>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const standingTypesResponse = z
  .object({
    name: z.string().optional(),
    description: z.string().optional(),
  })
  .transform((data) => ({
    name: data['name'],
    description: data['description'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const standingTypesRequest = z
  .object({ name: z.string().nullish(), description: z.string().nullish() })
  .transform((data) => ({
    name: data['name'],
    description: data['description'],
  }));
