// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scheduleGameContent = z.object({
  link: z.string().optional(),
});

/**
 *
 * @typedef  {ScheduleGameContent} scheduleGameContent
 * @property {string}
 */
export type ScheduleGameContent = z.infer<typeof scheduleGameContent>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scheduleGameContentResponse = z
  .object({
    link: z.string().optional(),
  })
  .transform((data) => ({
    link: data['link'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scheduleGameContentRequest = z.object({ link: z.string().nullish() }).transform((data) => ({
  link: data['link'],
}));
