// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { scheduleDay, scheduleDayRequest, scheduleDayResponse } from './schedule-day';

/**
 * The shape of the model inside the application code - what the users use
 */
export const schedule = z.object({
  copyright: z.string().optional(),
  totalItems: z.number().optional(),
  totalEvents: z.number().optional(),
  totalGames: z.number().optional(),
  totalMatches: z.number().optional(),
  wait: z.number().optional(),
  dates: z.array(scheduleDay).optional(),
});

/**
 *
 * @typedef  {Schedule} schedule
 * @property {string}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {ScheduleDay[]}
 */
export type Schedule = z.infer<typeof schedule>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scheduleResponse = z
  .object({
    copyright: z.string().optional(),
    totalItems: z.number().optional(),
    totalEvents: z.number().optional(),
    totalGames: z.number().optional(),
    totalMatches: z.number().optional(),
    wait: z.number().optional(),
    dates: z.array(scheduleDayResponse).optional(),
  })
  .transform((data) => ({
    copyright: data['copyright'],
    totalItems: data['totalItems'],
    totalEvents: data['totalEvents'],
    totalGames: data['totalGames'],
    totalMatches: data['totalMatches'],
    wait: data['wait'],
    dates: data['dates'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scheduleRequest = z
  .object({
    copyright: z.string().nullish(),
    totalItems: z.number().nullish(),
    totalEvents: z.number().nullish(),
    totalGames: z.number().nullish(),
    totalMatches: z.number().nullish(),
    wait: z.number().nullish(),
    dates: z.array(scheduleDayRequest).nullish(),
  })
  .transform((data) => ({
    copyright: data['copyright'],
    totalItems: data['totalItems'],
    totalEvents: data['totalEvents'],
    totalGames: data['totalGames'],
    totalMatches: data['totalMatches'],
    wait: data['wait'],
    dates: data['dates'],
  }));
