// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { awayLeagueRecord2, awayLeagueRecord2Request, awayLeagueRecord2Response } from './away-league-record-2';
import { awayTeam2, awayTeam2Request, awayTeam2Response } from './away-team-2';

/**
 * The shape of the model inside the application code - what the users use
 */
export const teamsAway2 = z.object({
  leagueRecord: awayLeagueRecord2.optional(),
  score: z.number().optional(),
  team: awayTeam2.optional(),
});

/**
 *
 * @typedef  {TeamsAway2} teamsAway2
 * @property {AwayLeagueRecord2}
 * @property {number}
 * @property {AwayTeam2}
 */
export type TeamsAway2 = z.infer<typeof teamsAway2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const teamsAway2Response = z
  .object({
    leagueRecord: awayLeagueRecord2Response.optional(),
    score: z.number().optional(),
    team: awayTeam2Response.optional(),
  })
  .transform((data) => ({
    leagueRecord: data['leagueRecord'],
    score: data['score'],
    team: data['team'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const teamsAway2Request = z
  .object({
    leagueRecord: awayLeagueRecord2Request.nullish(),
    score: z.number().nullish(),
    team: awayTeam2Request.nullish(),
  })
  .transform((data) => ({
    leagueRecord: data['leagueRecord'],
    score: data['score'],
    team: data['team'],
  }));
