// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const ticketType = z.enum([
  'buysell',
  'club buysell',
  'club mobile',
  'club mobile buysell',
  'club ticket',
  'mobile app ticket',
  'mobile buysell',
  'mobile ticket',
  'tablet app ticket',
  'ticket',
]);

export type TicketType = z.infer<typeof ticketType>;
