// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const conferenceName = z.enum(['Eastern', 'Western', 'World Cup of Hockey']);

export type ConferenceName = z.infer<typeof conferenceName>;
