// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { conferenceName } from './conference-name';
import { abbreviation } from './abbreviation';
import { shortName } from './short-name';

/**
 * The shape of the model inside the application code - what the users use
 */
export const conference = z.object({
  id: z.number().optional(),
  name: conferenceName.optional(),
  link: z.string().optional(),
  abbreviation: abbreviation.optional(),
  shortName: shortName.optional(),
  active: z.boolean().optional(),
});

/**
 *
 * @typedef  {Conference} conference
 * @property {number}
 * @property {ConferenceName}
 * @property {string}
 * @property {Abbreviation}
 * @property {ShortName}
 * @property {boolean}
 */
export type Conference = z.infer<typeof conference>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const conferenceResponse = z
  .object({
    id: z.number().optional(),
    name: conferenceName.optional(),
    link: z.string().optional(),
    abbreviation: abbreviation.optional(),
    shortName: shortName.optional(),
    active: z.boolean().optional(),
  })
  .transform((data) => ({
    id: data['id'],
    name: data['name'],
    link: data['link'],
    abbreviation: data['abbreviation'],
    shortName: data['shortName'],
    active: data['active'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const conferenceRequest = z
  .object({
    id: z.number().nullish(),
    name: conferenceName.nullish(),
    link: z.string().nullish(),
    abbreviation: abbreviation.nullish(),
    shortName: shortName.nullish(),
    active: z.boolean().nullish(),
  })
  .transform((data) => ({
    id: data['id'],
    name: data['name'],
    link: data['link'],
    abbreviation: data['abbreviation'],
    shortName: data['shortName'],
    active: data['active'],
  }));
