// This file was generated by liblab | https://liblab.com/

import { Nhl } from 'nhl';

(async () => {
  const nhl = new Nhl({});

  const { data } = await nhl.skaterStats.getCurrentSkaterStatsLeaders({
    categories: 'categories',
    limit: 2,
  });

  console.log(data);
})();
