// This file was generated by liblab | https://liblab.com/

import { Nhl } from 'nhl';

(async () => {
  const nhl = new Nhl({});

  const { data } = await nhl.conferences.getConferences();

  console.log(data);
})();
