// This file was generated by liblab | https://liblab.com/

import { NhlClient } from 'nhl_client';

(async () => {
  const nhlClient = new NhlClient({});

  const { data } = await nhlClient.skaterStats.getCurrentSkaterStatsLeaders({
    categories: 'categories',
    limit: 3,
  });

  console.log(data);
})();
