// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';

export class PlayerSpotlightService extends BaseService {
  /**
   * Retrieve information about players in the "spotlight".
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getPlayerSpotlight(requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = '/v1/player-spotlight';
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }
}
