// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';

export class RosterService extends BaseService {
  /**
   * Retrieve the roster for a specific team as of the current moment.
   * @param {string} team - Three-letter team code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getCurrentTeamRoster(team: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/roster/{team}/current', { team: team });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }

  /**
   * Retrieve the roster for a specific team and season.
   * @param {string} team - Three-letter team code
   * @param {number} season - Season in YYYYYYYY format
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamRosterBySeason(team: string, season: number, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/v1/roster/{team}/{season}', { team: team, season: season });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
    };
    return this.client.get(path, options);
  }
}
