// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const statTypesDisplayName = z.enum([
  'byDayOfWeek',
  'byDayOfWeekPlayoffs',
  'byMonth',
  'byMonthPlayoffs',
  'careerPlayoffs',
  'careerRegularSeason',
  'gameLog',
  'goalsByGameSituation',
  'goalsByGameSituationPlayoffs',
  'homeAndAway',
  'homeAndAwayPlayoffs',
  'onPaceRegularSeason',
  'playoffGameLog',
  'playoffStatRankings',
  'regularSeasonStatRankings',
  'statsSingleSeason',
  'statsSingleSeasonPlayoffs',
  'vsConference',
  'vsConferencePlayoffs',
  'vsDivision',
  'vsDivisionPlayoffs',
  'vsTeam',
  'vsTeamPlayoffs',
  'winLoss',
  'winLossPlayoffs',
  'yearByYear',
  'yearByYearPlayoffs',
  'yearByYearPlayoffsRank',
  'yearByYearRank',
]);

export type StatTypesDisplayName = z.infer<typeof statTypesDisplayName>;
