// This file was generated by liblab | https://liblab.com/

import { GetPlayerStatsStats, getPlayerStatsStats } from './models';

export interface GetPlayerStatsParams {
  stats: GetPlayerStatsStats;
  season?: number;
}
