// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getPlayerStatsStats = z.enum([
  'homeAndAway',
  'byDayOfWeek',
  'byMonth',
  'goalsByGameSituation',
  'onPaceRegularSeason',
  'regularSeasonStatRankings',
  'statsSingleSeason',
  'vsConference',
  'vsDivision',
  'vsTeam',
  'winLoss',
]);

export type GetPlayerStatsStats = z.infer<typeof getPlayerStatsStats>;
