// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { playerStatsStats, playerStatsStatsRequest, playerStatsStatsResponse } from './player-stats-stats';

/**
 * The shape of the model inside the application code - what the users use
 */
export const playerStats = z.object({
  copyright: z.string().optional(),
  stats: z.array(playerStatsStats).optional(),
});

/**
 *
 * @typedef  {PlayerStats} playerStats
 * @property {string}
 * @property {PlayerStatsStats[]}
 */
export type PlayerStats = z.infer<typeof playerStats>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const playerStatsResponse = z
  .object({
    copyright: z.string().optional(),
    stats: z.array(playerStatsStatsResponse).optional(),
  })
  .transform((data) => ({
    copyright: data['copyright'],
    stats: data['stats'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const playerStatsRequest = z
  .object({ copyright: z.string().nullish(), stats: z.array(playerStatsStatsRequest).nullish() })
  .transform((data) => ({
    copyright: data['copyright'],
    stats: data['stats'],
  }));
