// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Divisions, divisionsResponse } from './models';
import { Division, divisionResponse } from '../common';

export class DivisionsService extends BaseService {
  /**
   * This only retrieves active divisions. For inactive divisions, use `/divisions/{id}`.
   * @returns {Promise<HttpResponse<Divisions>>} OK
   */
  async getDivisions(requestConfig?: RequestConfig): Promise<HttpResponse<Divisions>> {
    const path = '/divisions';
    const options: any = {
      responseSchema: divisionsResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
   * You can use this to also retrieve inactive divisions. For example, the ID for the old Patrick division is `13`.
   * @param {number} id - The ID of the division.
   * @returns {Promise<HttpResponse<Division>>} OK
   */
  async getDivision(id: number, requestConfig?: RequestConfig): Promise<HttpResponse<Division>> {
    const path = this.client.buildPath('/divisions/{id}', { id: id });
    const options: any = {
      responseSchema: divisionResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
