// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { PlayerService } from './services/player';
import { SkaterStatsService } from './services/skater-stats';
import { GoalieStatsService } from './services/goalie-stats';
import { PlayerSpotlightService } from './services/player-spotlight';
import { StandingsService } from './services/standings';
import { ClubStatsService } from './services/club-stats';
import { ScoreboardService } from './services/scoreboard';
import { RosterService } from './services/roster';
import { ScheduleService } from './services/schedule';

export class NhlClient {
  public readonly player: PlayerService;

  public readonly skaterStats: SkaterStatsService;

  public readonly goalieStats: GoalieStatsService;

  public readonly playerSpotlight: PlayerSpotlightService;

  public readonly standings: StandingsService;

  public readonly clubStats: ClubStatsService;

  public readonly scoreboard: ScoreboardService;

  public readonly roster: RosterService;

  public readonly schedule: ScheduleService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.player = new PlayerService(this.config);

    this.skaterStats = new SkaterStatsService(this.config);

    this.goalieStats = new GoalieStatsService(this.config);

    this.playerSpotlight = new PlayerSpotlightService(this.config);

    this.standings = new StandingsService(this.config);

    this.clubStats = new ClubStatsService(this.config);

    this.scoreboard = new ScoreboardService(this.config);

    this.roster = new RosterService(this.config);

    this.schedule = new ScheduleService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.player.baseUrl = baseUrl;
    this.skaterStats.baseUrl = baseUrl;
    this.goalieStats.baseUrl = baseUrl;
    this.playerSpotlight.baseUrl = baseUrl;
    this.standings.baseUrl = baseUrl;
    this.clubStats.baseUrl = baseUrl;
    this.scoreboard.baseUrl = baseUrl;
    this.roster.baseUrl = baseUrl;
    this.schedule.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.player.baseUrl = environment;
    this.skaterStats.baseUrl = environment;
    this.goalieStats.baseUrl = environment;
    this.playerSpotlight.baseUrl = environment;
    this.standings.baseUrl = environment;
    this.clubStats.baseUrl = environment;
    this.scoreboard.baseUrl = environment;
    this.roster.baseUrl = environment;
    this.schedule.baseUrl = environment;
  }

  set timeout(timeout: number) {
    this.player.timeout = timeout;
    this.skaterStats.timeout = timeout;
    this.goalieStats.timeout = timeout;
    this.playerSpotlight.timeout = timeout;
    this.standings.timeout = timeout;
    this.clubStats.timeout = timeout;
    this.scoreboard.timeout = timeout;
    this.roster.timeout = timeout;
    this.schedule.timeout = timeout;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
