// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { ConferencesService } from './services/conferences';
import { DivisionsService } from './services/divisions';
import { DraftService } from './services/draft';
import { GamesService } from './services/games';
import { PlayersService } from './services/players';
import { ScheduleService } from './services/schedule';
import { StandingsService } from './services/standings';
import { StatsService } from './services/stats';
import { TeamsService } from './services/teams';

export class Nhl {
  public readonly conferences: ConferencesService;

  public readonly divisions: DivisionsService;

  public readonly draft: DraftService;

  public readonly games: GamesService;

  public readonly players: PlayersService;

  public readonly schedule: ScheduleService;

  public readonly standings: StandingsService;

  public readonly stats: StatsService;

  public readonly teams: TeamsService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.conferences = new ConferencesService(this.config);

    this.divisions = new DivisionsService(this.config);

    this.draft = new DraftService(this.config);

    this.games = new GamesService(this.config);

    this.players = new PlayersService(this.config);

    this.schedule = new ScheduleService(this.config);

    this.standings = new StandingsService(this.config);

    this.stats = new StatsService(this.config);

    this.teams = new TeamsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.conferences.baseUrl = baseUrl;
    this.divisions.baseUrl = baseUrl;
    this.draft.baseUrl = baseUrl;
    this.games.baseUrl = baseUrl;
    this.players.baseUrl = baseUrl;
    this.schedule.baseUrl = baseUrl;
    this.standings.baseUrl = baseUrl;
    this.stats.baseUrl = baseUrl;
    this.teams.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.conferences.baseUrl = environment;
    this.divisions.baseUrl = environment;
    this.draft.baseUrl = environment;
    this.games.baseUrl = environment;
    this.players.baseUrl = environment;
    this.schedule.baseUrl = environment;
    this.standings.baseUrl = environment;
    this.stats.baseUrl = environment;
    this.teams.baseUrl = environment;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
