// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { roster, rosterRequest, rosterResponse } from '../../common/roster';

/**
 * The shape of the model inside the application code - what the users use
 */
export const rosters = z.object({
  copyright: z.string().optional(),
  teams: z.array(roster).optional(),
});

/**
 *
 * @typedef  {Rosters} rosters
 * @property {string}
 * @property {Roster[]}
 */
export type Rosters = z.infer<typeof rosters>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const rostersResponse = z
  .object({
    copyright: z.string().optional(),
    teams: z.array(rosterResponse).optional(),
  })
  .transform((data) => ({
    copyright: data['copyright'],
    teams: data['teams'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const rostersRequest = z
  .object({ copyright: z.string().nullish(), teams: z.array(rosterRequest).nullish() })
  .transform((data) => ({
    copyright: data['copyright'],
    teams: data['teams'],
  }));
