// This file was generated by liblab | https://liblab.com/

import { GetTeamsExpand, getTeamsExpand } from '../common';

export interface GetTeamsParams {
  expand?: GetTeamsExpand;
  season?: number;
}

export interface GetTeamParams {
  expand?: GetTeamsExpand;
  season?: number;
}

export interface GetTeamRosterParams {
  season?: number;
}
