// This file was generated by liblab | https://liblab.com/

export interface GetCurrentSkaterStatsLeadersParams {
  categories?: string;
  limit?: number;
}

export interface GetSkaterStatsLeadersParams {
  categories?: string;
  limit?: number;
}
